services:

  jekyll:

    build:
      context: .devcontainer

    working_dir: /workspace

    ports:
      - "4000:4000"
      - "35729:35729"

    volumes:
      - .:/workspace
      - bundle_cache:/usr/local/bundle

    command: >
      bash -c "
      bundle install &&
      bundle exec jekyll serve
      --host 0.0.0.0
      --livereload
      --incremental
      --force_polling
      "

volumes:
  bundle_cache:
